// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: ticket-api/api/model.proto

package ticket_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TicketModel struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Uuid             string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	MovieScreeningId string                 `protobuf:"bytes,2,opt,name=movie_screening_id,json=movieScreeningId,proto3" json:"movie_screening_id,omitempty"`
	TheaterSeatingId string                 `protobuf:"bytes,3,opt,name=theater_seating_id,json=theaterSeatingId,proto3" json:"theater_seating_id,omitempty"`
	Price            float32                `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TicketModel) Reset() {
	*x = TicketModel{}
	mi := &file_ticket_api_api_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketModel) ProtoMessage() {}

func (x *TicketModel) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_api_api_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketModel.ProtoReflect.Descriptor instead.
func (*TicketModel) Descriptor() ([]byte, []int) {
	return file_ticket_api_api_model_proto_rawDescGZIP(), []int{0}
}

func (x *TicketModel) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *TicketModel) GetMovieScreeningId() string {
	if x != nil {
		return x.MovieScreeningId
	}
	return ""
}

func (x *TicketModel) GetTheaterSeatingId() string {
	if x != nil {
		return x.TheaterSeatingId
	}
	return ""
}

func (x *TicketModel) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_ticket_api_api_model_proto protoreflect.FileDescriptor

const file_ticket_api_api_model_proto_rawDesc = "" +
	"\n" +
	"\x1aticket-api/api/model.proto\x12\x05model\"\x93\x01\n" +
	"\vTicketModel\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12,\n" +
	"\x12movie_screening_id\x18\x02 \x01(\tR\x10movieScreeningId\x12,\n" +
	"\x12theater_seating_id\x18\x03 \x01(\tR\x10theaterSeatingId\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x02R\x05priceB\x1fZ\x1d./ticket-api/proto;ticket_apib\x06proto3"

var (
	file_ticket_api_api_model_proto_rawDescOnce sync.Once
	file_ticket_api_api_model_proto_rawDescData []byte
)

func file_ticket_api_api_model_proto_rawDescGZIP() []byte {
	file_ticket_api_api_model_proto_rawDescOnce.Do(func() {
		file_ticket_api_api_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ticket_api_api_model_proto_rawDesc), len(file_ticket_api_api_model_proto_rawDesc)))
	})
	return file_ticket_api_api_model_proto_rawDescData
}

var file_ticket_api_api_model_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ticket_api_api_model_proto_goTypes = []any{
	(*TicketModel)(nil), // 0: model.TicketModel
}
var file_ticket_api_api_model_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ticket_api_api_model_proto_init() }
func file_ticket_api_api_model_proto_init() {
	if File_ticket_api_api_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ticket_api_api_model_proto_rawDesc), len(file_ticket_api_api_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ticket_api_api_model_proto_goTypes,
		DependencyIndexes: file_ticket_api_api_model_proto_depIdxs,
		MessageInfos:      file_ticket_api_api_model_proto_msgTypes,
	}.Build()
	File_ticket_api_api_model_proto = out.File
	file_ticket_api_api_model_proto_goTypes = nil
	file_ticket_api_api_model_proto_depIdxs = nil
}
