// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: ticket-api/api/ticket.proto

package ticket_api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTicketReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MovieScreening string                 `protobuf:"bytes,1,opt,name=movie_screening,json=movieScreening,proto3" json:"movie_screening,omitempty"`
	Data           []*TicketModel         `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateTicketReq) Reset() {
	*x = CreateTicketReq{}
	mi := &file_ticket_api_api_ticket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTicketReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTicketReq) ProtoMessage() {}

func (x *CreateTicketReq) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_api_api_ticket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTicketReq.ProtoReflect.Descriptor instead.
func (*CreateTicketReq) Descriptor() ([]byte, []int) {
	return file_ticket_api_api_ticket_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTicketReq) GetMovieScreening() string {
	if x != nil {
		return x.MovieScreening
	}
	return ""
}

func (x *CreateTicketReq) GetData() []*TicketModel {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateTicketRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          []string               `protobuf:"bytes,1,rep,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTicketRes) Reset() {
	*x = CreateTicketRes{}
	mi := &file_ticket_api_api_ticket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTicketRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTicketRes) ProtoMessage() {}

func (x *CreateTicketRes) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_api_api_ticket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTicketRes.ProtoReflect.Descriptor instead.
func (*CreateTicketRes) Descriptor() ([]byte, []int) {
	return file_ticket_api_api_ticket_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTicketRes) GetUuid() []string {
	if x != nil {
		return x.Uuid
	}
	return nil
}

var File_ticket_api_api_ticket_proto protoreflect.FileDescriptor

const file_ticket_api_api_ticket_proto_rawDesc = "" +
	"\n" +
	"\x1bticket-api/api/ticket.proto\x12\x06ticket\x1a\x1aticket-api/api/model.proto\x1a(third-party/google/api/annotations.proto\"b\n" +
	"\x0fCreateTicketReq\x12'\n" +
	"\x0fmovie_screening\x18\x01 \x01(\tR\x0emovieScreening\x12&\n" +
	"\x04data\x18\x02 \x03(\v2\x12.model.TicketModelR\x04data\"%\n" +
	"\x0fCreateTicketRes\x12\x12\n" +
	"\x04uuid\x18\x01 \x03(\tR\x04uuid2m\n" +
	"\rTicketService\x12\\\n" +
	"\x06Create\x12\x17.ticket.CreateTicketReq\x1a\x17.ticket.CreateTicketRes\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/ticket/createB\x1fZ\x1d./ticket-api/proto;ticket_apib\x06proto3"

var (
	file_ticket_api_api_ticket_proto_rawDescOnce sync.Once
	file_ticket_api_api_ticket_proto_rawDescData []byte
)

func file_ticket_api_api_ticket_proto_rawDescGZIP() []byte {
	file_ticket_api_api_ticket_proto_rawDescOnce.Do(func() {
		file_ticket_api_api_ticket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ticket_api_api_ticket_proto_rawDesc), len(file_ticket_api_api_ticket_proto_rawDesc)))
	})
	return file_ticket_api_api_ticket_proto_rawDescData
}

var file_ticket_api_api_ticket_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ticket_api_api_ticket_proto_goTypes = []any{
	(*CreateTicketReq)(nil), // 0: ticket.CreateTicketReq
	(*CreateTicketRes)(nil), // 1: ticket.CreateTicketRes
	(*TicketModel)(nil),     // 2: model.TicketModel
}
var file_ticket_api_api_ticket_proto_depIdxs = []int32{
	2, // 0: ticket.CreateTicketReq.data:type_name -> model.TicketModel
	0, // 1: ticket.TicketService.Create:input_type -> ticket.CreateTicketReq
	1, // 2: ticket.TicketService.Create:output_type -> ticket.CreateTicketRes
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ticket_api_api_ticket_proto_init() }
func file_ticket_api_api_ticket_proto_init() {
	if File_ticket_api_api_ticket_proto != nil {
		return
	}
	file_ticket_api_api_model_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ticket_api_api_ticket_proto_rawDesc), len(file_ticket_api_api_ticket_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ticket_api_api_ticket_proto_goTypes,
		DependencyIndexes: file_ticket_api_api_ticket_proto_depIdxs,
		MessageInfos:      file_ticket_api_api_ticket_proto_msgTypes,
	}.Build()
	File_ticket_api_api_ticket_proto = out.File
	file_ticket_api_api_ticket_proto_goTypes = nil
	file_ticket_api_api_ticket_proto_depIdxs = nil
}
