// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: manager-api/api/category.proto

package manager_api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCategoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *CategoryModel         `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryReq) Reset() {
	*x = CreateCategoryReq{}
	mi := &file_manager_api_api_category_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryReq) ProtoMessage() {}

func (x *CreateCategoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_manager_api_api_category_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryReq.ProtoReflect.Descriptor instead.
func (*CreateCategoryReq) Descriptor() ([]byte, []int) {
	return file_manager_api_api_category_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCategoryReq) GetData() *CategoryModel {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateCategoryRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *CategoryModel         `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryRes) Reset() {
	*x = CreateCategoryRes{}
	mi := &file_manager_api_api_category_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryRes) ProtoMessage() {}

func (x *CreateCategoryRes) ProtoReflect() protoreflect.Message {
	mi := &file_manager_api_api_category_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryRes.ProtoReflect.Descriptor instead.
func (*CreateCategoryRes) Descriptor() ([]byte, []int) {
	return file_manager_api_api_category_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCategoryRes) GetData() *CategoryModel {
	if x != nil {
		return x.Data
	}
	return nil
}

type CategoryFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryFilter) Reset() {
	*x = CategoryFilter{}
	mi := &file_manager_api_api_category_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryFilter) ProtoMessage() {}

func (x *CategoryFilter) ProtoReflect() protoreflect.Message {
	mi := &file_manager_api_api_category_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryFilter.ProtoReflect.Descriptor instead.
func (*CategoryFilter) Descriptor() ([]byte, []int) {
	return file_manager_api_api_category_proto_rawDescGZIP(), []int{2}
}

func (x *CategoryFilter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryFilter) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ListCategoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilterBase    *FilterBase            `protobuf:"bytes,1,opt,name=filter_base,json=filterBase,proto3" json:"filter_base,omitempty"`
	Filter        *CategoryFilter        `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoryReq) Reset() {
	*x = ListCategoryReq{}
	mi := &file_manager_api_api_category_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoryReq) ProtoMessage() {}

func (x *ListCategoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_manager_api_api_category_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoryReq.ProtoReflect.Descriptor instead.
func (*ListCategoryReq) Descriptor() ([]byte, []int) {
	return file_manager_api_api_category_proto_rawDescGZIP(), []int{3}
}

func (x *ListCategoryReq) GetFilterBase() *FilterBase {
	if x != nil {
		return x.FilterBase
	}
	return nil
}

func (x *ListCategoryReq) GetFilter() *CategoryFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListCategoryRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*CategoryModel       `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoryRes) Reset() {
	*x = ListCategoryRes{}
	mi := &file_manager_api_api_category_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoryRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoryRes) ProtoMessage() {}

func (x *ListCategoryRes) ProtoReflect() protoreflect.Message {
	mi := &file_manager_api_api_category_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoryRes.ProtoReflect.Descriptor instead.
func (*ListCategoryRes) Descriptor() ([]byte, []int) {
	return file_manager_api_api_category_proto_rawDescGZIP(), []int{4}
}

func (x *ListCategoryRes) GetData() []*CategoryModel {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_manager_api_api_category_proto protoreflect.FileDescriptor

const file_manager_api_api_category_proto_rawDesc = "" +
	"\n" +
	"\x1emanager-api/api/category.proto\x12\bcategory\x1a\x1bmanager-api/api/model.proto\x1a\x1cmanager-api/api/common.proto\x1a(third-party/google/api/annotations.proto\"=\n" +
	"\x11CreateCategoryReq\x12(\n" +
	"\x04data\x18\x01 \x01(\v2\x14.model.CategoryModelR\x04data\"=\n" +
	"\x11CreateCategoryRes\x12(\n" +
	"\x04data\x18\x01 \x01(\v2\x14.model.CategoryModelR\x04data\"8\n" +
	"\x0eCategoryFilter\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"x\n" +
	"\x0fListCategoryReq\x123\n" +
	"\vfilter_base\x18\x01 \x01(\v2\x12.common.FilterBaseR\n" +
	"filterBase\x120\n" +
	"\x06filter\x18\x02 \x01(\v2\x18.category.CategoryFilterR\x06filter\";\n" +
	"\x0fListCategoryRes\x12(\n" +
	"\x04data\x18\x01 \x03(\v2\x14.model.CategoryModelR\x04data2\xcb\x01\n" +
	"\bCategory\x12_\n" +
	"\x06Create\x12\x1b.category.CreateCategoryReq\x1a\x1b.category.CreateCategoryRes\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/category\x12^\n" +
	"\x04List\x12\x19.category.ListCategoryReq\x1a\x19.category.ListCategoryRes\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/category/listB!Z\x1f./manager-api/proto;manager_apib\x06proto3"

var (
	file_manager_api_api_category_proto_rawDescOnce sync.Once
	file_manager_api_api_category_proto_rawDescData []byte
)

func file_manager_api_api_category_proto_rawDescGZIP() []byte {
	file_manager_api_api_category_proto_rawDescOnce.Do(func() {
		file_manager_api_api_category_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_manager_api_api_category_proto_rawDesc), len(file_manager_api_api_category_proto_rawDesc)))
	})
	return file_manager_api_api_category_proto_rawDescData
}

var file_manager_api_api_category_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_manager_api_api_category_proto_goTypes = []any{
	(*CreateCategoryReq)(nil), // 0: category.CreateCategoryReq
	(*CreateCategoryRes)(nil), // 1: category.CreateCategoryRes
	(*CategoryFilter)(nil),    // 2: category.CategoryFilter
	(*ListCategoryReq)(nil),   // 3: category.ListCategoryReq
	(*ListCategoryRes)(nil),   // 4: category.ListCategoryRes
	(*CategoryModel)(nil),     // 5: model.CategoryModel
	(*FilterBase)(nil),        // 6: common.FilterBase
}
var file_manager_api_api_category_proto_depIdxs = []int32{
	5, // 0: category.CreateCategoryReq.data:type_name -> model.CategoryModel
	5, // 1: category.CreateCategoryRes.data:type_name -> model.CategoryModel
	6, // 2: category.ListCategoryReq.filter_base:type_name -> common.FilterBase
	2, // 3: category.ListCategoryReq.filter:type_name -> category.CategoryFilter
	5, // 4: category.ListCategoryRes.data:type_name -> model.CategoryModel
	0, // 5: category.Category.Create:input_type -> category.CreateCategoryReq
	3, // 6: category.Category.List:input_type -> category.ListCategoryReq
	1, // 7: category.Category.Create:output_type -> category.CreateCategoryRes
	4, // 8: category.Category.List:output_type -> category.ListCategoryRes
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_manager_api_api_category_proto_init() }
func file_manager_api_api_category_proto_init() {
	if File_manager_api_api_category_proto != nil {
		return
	}
	file_manager_api_api_model_proto_init()
	file_manager_api_api_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_manager_api_api_category_proto_rawDesc), len(file_manager_api_api_category_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_manager_api_api_category_proto_goTypes,
		DependencyIndexes: file_manager_api_api_category_proto_depIdxs,
		MessageInfos:      file_manager_api_api_category_proto_msgTypes,
	}.Build()
	File_manager_api_api_category_proto = out.File
	file_manager_api_api_category_proto_goTypes = nil
	file_manager_api_api_category_proto_depIdxs = nil
}
