// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: manager-api/api/cinema_room.proto

package manager_api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// api: create cinema room
type CreateCinemaRoomReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MovieTheaterId string                 `protobuf:"bytes,1,opt,name=movie_theater_id,json=movieTheaterId,proto3" json:"movie_theater_id,omitempty"`
	Code           string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateCinemaRoomReq) Reset() {
	*x = CreateCinemaRoomReq{}
	mi := &file_manager_api_api_cinema_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCinemaRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCinemaRoomReq) ProtoMessage() {}

func (x *CreateCinemaRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_manager_api_api_cinema_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCinemaRoomReq.ProtoReflect.Descriptor instead.
func (*CreateCinemaRoomReq) Descriptor() ([]byte, []int) {
	return file_manager_api_api_cinema_room_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCinemaRoomReq) GetMovieTheaterId() string {
	if x != nil {
		return x.MovieTheaterId
	}
	return ""
}

func (x *CreateCinemaRoomReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type CreateCinemaRoomRes struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Uuid           string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	MovieTheaterId string                 `protobuf:"bytes,2,opt,name=movie_theater_id,json=movieTheaterId,proto3" json:"movie_theater_id,omitempty"`
	Code           string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateCinemaRoomRes) Reset() {
	*x = CreateCinemaRoomRes{}
	mi := &file_manager_api_api_cinema_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCinemaRoomRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCinemaRoomRes) ProtoMessage() {}

func (x *CreateCinemaRoomRes) ProtoReflect() protoreflect.Message {
	mi := &file_manager_api_api_cinema_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCinemaRoomRes.ProtoReflect.Descriptor instead.
func (*CreateCinemaRoomRes) Descriptor() ([]byte, []int) {
	return file_manager_api_api_cinema_room_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCinemaRoomRes) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *CreateCinemaRoomRes) GetMovieTheaterId() string {
	if x != nil {
		return x.MovieTheaterId
	}
	return ""
}

func (x *CreateCinemaRoomRes) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// api: update cinema room
type UpdateCinemaRoomReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCinemaRoomReq) Reset() {
	*x = UpdateCinemaRoomReq{}
	mi := &file_manager_api_api_cinema_room_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCinemaRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCinemaRoomReq) ProtoMessage() {}

func (x *UpdateCinemaRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_manager_api_api_cinema_room_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCinemaRoomReq.ProtoReflect.Descriptor instead.
func (*UpdateCinemaRoomReq) Descriptor() ([]byte, []int) {
	return file_manager_api_api_cinema_room_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateCinemaRoomReq) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UpdateCinemaRoomReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type UpdateCinemaRoomRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCinemaRoomRes) Reset() {
	*x = UpdateCinemaRoomRes{}
	mi := &file_manager_api_api_cinema_room_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCinemaRoomRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCinemaRoomRes) ProtoMessage() {}

func (x *UpdateCinemaRoomRes) ProtoReflect() protoreflect.Message {
	mi := &file_manager_api_api_cinema_room_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCinemaRoomRes.ProtoReflect.Descriptor instead.
func (*UpdateCinemaRoomRes) Descriptor() ([]byte, []int) {
	return file_manager_api_api_cinema_room_proto_rawDescGZIP(), []int{3}
}

// api: detail cinema room
type DetailCinemaRoomReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailCinemaRoomReq) Reset() {
	*x = DetailCinemaRoomReq{}
	mi := &file_manager_api_api_cinema_room_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailCinemaRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailCinemaRoomReq) ProtoMessage() {}

func (x *DetailCinemaRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_manager_api_api_cinema_room_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailCinemaRoomReq.ProtoReflect.Descriptor instead.
func (*DetailCinemaRoomReq) Descriptor() ([]byte, []int) {
	return file_manager_api_api_cinema_room_proto_rawDescGZIP(), []int{4}
}

func (x *DetailCinemaRoomReq) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type DetailCinemaRoomRes struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Uuid           string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	MovieTheaterId string                 `protobuf:"bytes,2,opt,name=movie_theater_id,json=movieTheaterId,proto3" json:"movie_theater_id,omitempty"`
	Code           string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DetailCinemaRoomRes) Reset() {
	*x = DetailCinemaRoomRes{}
	mi := &file_manager_api_api_cinema_room_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailCinemaRoomRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailCinemaRoomRes) ProtoMessage() {}

func (x *DetailCinemaRoomRes) ProtoReflect() protoreflect.Message {
	mi := &file_manager_api_api_cinema_room_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailCinemaRoomRes.ProtoReflect.Descriptor instead.
func (*DetailCinemaRoomRes) Descriptor() ([]byte, []int) {
	return file_manager_api_api_cinema_room_proto_rawDescGZIP(), []int{5}
}

func (x *DetailCinemaRoomRes) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *DetailCinemaRoomRes) GetMovieTheaterId() string {
	if x != nil {
		return x.MovieTheaterId
	}
	return ""
}

func (x *DetailCinemaRoomRes) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DetailCinemaRoomRes) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *DetailCinemaRoomRes) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// api: list cinema room
type FilterCinemaRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterCinemaRoom) Reset() {
	*x = FilterCinemaRoom{}
	mi := &file_manager_api_api_cinema_room_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterCinemaRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterCinemaRoom) ProtoMessage() {}

func (x *FilterCinemaRoom) ProtoReflect() protoreflect.Message {
	mi := &file_manager_api_api_cinema_room_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterCinemaRoom.ProtoReflect.Descriptor instead.
func (*FilterCinemaRoom) Descriptor() ([]byte, []int) {
	return file_manager_api_api_cinema_room_proto_rawDescGZIP(), []int{6}
}

func (x *FilterCinemaRoom) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ListCinemaRoomReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilterBase    *FilterBase            `protobuf:"bytes,1,opt,name=filter_base,json=filterBase,proto3" json:"filter_base,omitempty"`
	Filter        *FilterCinemaRoom      `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCinemaRoomReq) Reset() {
	*x = ListCinemaRoomReq{}
	mi := &file_manager_api_api_cinema_room_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCinemaRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCinemaRoomReq) ProtoMessage() {}

func (x *ListCinemaRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_manager_api_api_cinema_room_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCinemaRoomReq.ProtoReflect.Descriptor instead.
func (*ListCinemaRoomReq) Descriptor() ([]byte, []int) {
	return file_manager_api_api_cinema_room_proto_rawDescGZIP(), []int{7}
}

func (x *ListCinemaRoomReq) GetFilterBase() *FilterBase {
	if x != nil {
		return x.FilterBase
	}
	return nil
}

func (x *ListCinemaRoomReq) GetFilter() *FilterCinemaRoom {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListCinemaRoomRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*CinemaRoomModel     `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCinemaRoomRes) Reset() {
	*x = ListCinemaRoomRes{}
	mi := &file_manager_api_api_cinema_room_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCinemaRoomRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCinemaRoomRes) ProtoMessage() {}

func (x *ListCinemaRoomRes) ProtoReflect() protoreflect.Message {
	mi := &file_manager_api_api_cinema_room_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCinemaRoomRes.ProtoReflect.Descriptor instead.
func (*ListCinemaRoomRes) Descriptor() ([]byte, []int) {
	return file_manager_api_api_cinema_room_proto_rawDescGZIP(), []int{8}
}

func (x *ListCinemaRoomRes) GetData() []*CinemaRoomModel {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListCinemaRoomRes) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_manager_api_api_cinema_room_proto protoreflect.FileDescriptor

const file_manager_api_api_cinema_room_proto_rawDesc = "" +
	"\n" +
	"!manager-api/api/cinema_room.proto\x12\vcinema_room\x1a(third-party/google/api/annotations.proto\x1a\x1cmanager-api/api/common.proto\x1a\x1bmanager-api/api/model.proto\"S\n" +
	"\x13CreateCinemaRoomReq\x12(\n" +
	"\x10movie_theater_id\x18\x01 \x01(\tR\x0emovieTheaterId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"g\n" +
	"\x13CreateCinemaRoomRes\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12(\n" +
	"\x10movie_theater_id\x18\x02 \x01(\tR\x0emovieTheaterId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"=\n" +
	"\x13UpdateCinemaRoomReq\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"\x15\n" +
	"\x13UpdateCinemaRoomRes\")\n" +
	"\x13DetailCinemaRoomReq\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\xa5\x01\n" +
	"\x13DetailCinemaRoomRes\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12(\n" +
	"\x10movie_theater_id\x18\x02 \x01(\tR\x0emovieTheaterId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\"&\n" +
	"\x10FilterCinemaRoom\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"\x7f\n" +
	"\x11ListCinemaRoomReq\x123\n" +
	"\vfilter_base\x18\x01 \x01(\v2\x12.common.FilterBaseR\n" +
	"filterBase\x125\n" +
	"\x06filter\x18\x02 \x01(\v2\x1d.cinema_room.FilterCinemaRoomR\x06filter\"U\n" +
	"\x11ListCinemaRoomRes\x12*\n" +
	"\x04data\x18\x01 \x03(\v2\x16.model.CinemaRoomModelR\x04data\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2\xd7\x03\n" +
	"\x11CinemaRoomService\x12s\n" +
	"\x06Create\x12 .cinema_room.CreateCinemaRoomReq\x1a .cinema_room.CreateCinemaRoomRes\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/cinema-room/create\x12s\n" +
	"\x06Update\x12 .cinema_room.UpdateCinemaRoomReq\x1a .cinema_room.UpdateCinemaRoomRes\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\x1a\x1a/api/v1/cinema-room/update\x12p\n" +
	"\x06Detail\x12 .cinema_room.DetailCinemaRoomReq\x1a .cinema_room.DetailCinemaRoomRes\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1/cinema-room/{uuid}\x12f\n" +
	"\x04List\x12\x1e.cinema_room.ListCinemaRoomReq\x1a\x1e.cinema_room.ListCinemaRoomRes\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/cinema-roomB!Z\x1f./manager-api/proto;manager_apib\x06proto3"

var (
	file_manager_api_api_cinema_room_proto_rawDescOnce sync.Once
	file_manager_api_api_cinema_room_proto_rawDescData []byte
)

func file_manager_api_api_cinema_room_proto_rawDescGZIP() []byte {
	file_manager_api_api_cinema_room_proto_rawDescOnce.Do(func() {
		file_manager_api_api_cinema_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_manager_api_api_cinema_room_proto_rawDesc), len(file_manager_api_api_cinema_room_proto_rawDesc)))
	})
	return file_manager_api_api_cinema_room_proto_rawDescData
}

var file_manager_api_api_cinema_room_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_manager_api_api_cinema_room_proto_goTypes = []any{
	(*CreateCinemaRoomReq)(nil), // 0: cinema_room.CreateCinemaRoomReq
	(*CreateCinemaRoomRes)(nil), // 1: cinema_room.CreateCinemaRoomRes
	(*UpdateCinemaRoomReq)(nil), // 2: cinema_room.UpdateCinemaRoomReq
	(*UpdateCinemaRoomRes)(nil), // 3: cinema_room.UpdateCinemaRoomRes
	(*DetailCinemaRoomReq)(nil), // 4: cinema_room.DetailCinemaRoomReq
	(*DetailCinemaRoomRes)(nil), // 5: cinema_room.DetailCinemaRoomRes
	(*FilterCinemaRoom)(nil),    // 6: cinema_room.FilterCinemaRoom
	(*ListCinemaRoomReq)(nil),   // 7: cinema_room.ListCinemaRoomReq
	(*ListCinemaRoomRes)(nil),   // 8: cinema_room.ListCinemaRoomRes
	(*FilterBase)(nil),          // 9: common.FilterBase
	(*CinemaRoomModel)(nil),     // 10: model.CinemaRoomModel
}
var file_manager_api_api_cinema_room_proto_depIdxs = []int32{
	9,  // 0: cinema_room.ListCinemaRoomReq.filter_base:type_name -> common.FilterBase
	6,  // 1: cinema_room.ListCinemaRoomReq.filter:type_name -> cinema_room.FilterCinemaRoom
	10, // 2: cinema_room.ListCinemaRoomRes.data:type_name -> model.CinemaRoomModel
	0,  // 3: cinema_room.CinemaRoomService.Create:input_type -> cinema_room.CreateCinemaRoomReq
	2,  // 4: cinema_room.CinemaRoomService.Update:input_type -> cinema_room.UpdateCinemaRoomReq
	4,  // 5: cinema_room.CinemaRoomService.Detail:input_type -> cinema_room.DetailCinemaRoomReq
	7,  // 6: cinema_room.CinemaRoomService.List:input_type -> cinema_room.ListCinemaRoomReq
	1,  // 7: cinema_room.CinemaRoomService.Create:output_type -> cinema_room.CreateCinemaRoomRes
	3,  // 8: cinema_room.CinemaRoomService.Update:output_type -> cinema_room.UpdateCinemaRoomRes
	5,  // 9: cinema_room.CinemaRoomService.Detail:output_type -> cinema_room.DetailCinemaRoomRes
	8,  // 10: cinema_room.CinemaRoomService.List:output_type -> cinema_room.ListCinemaRoomRes
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_manager_api_api_cinema_room_proto_init() }
func file_manager_api_api_cinema_room_proto_init() {
	if File_manager_api_api_cinema_room_proto != nil {
		return
	}
	file_manager_api_api_common_proto_init()
	file_manager_api_api_model_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_manager_api_api_cinema_room_proto_rawDesc), len(file_manager_api_api_cinema_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_manager_api_api_cinema_room_proto_goTypes,
		DependencyIndexes: file_manager_api_api_cinema_room_proto_depIdxs,
		MessageInfos:      file_manager_api_api_cinema_room_proto_msgTypes,
	}.Build()
	File_manager_api_api_cinema_room_proto = out.File
	file_manager_api_api_cinema_room_proto_goTypes = nil
	file_manager_api_api_cinema_room_proto_depIdxs = nil
}
