// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: manager-api/api/health.proto

package manager_api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_manager_api_api_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_manager_api_api_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_manager_api_api_health_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mess          string                 `protobuf:"bytes,1,opt,name=mess,proto3" json:"mess,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_manager_api_api_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_manager_api_api_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_manager_api_api_health_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetMess() string {
	if x != nil {
		return x.Mess
	}
	return ""
}

var File_manager_api_api_health_proto protoreflect.FileDescriptor

const file_manager_api_api_health_proto_rawDesc = "" +
	"\n" +
	"\x1cmanager-api/api/health.proto\x12\x06health\x1a(third-party/google/api/annotations.proto\"1\n" +
	"\aRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x1e\n" +
	"\bResponse\x12\x12\n" +
	"\x04mess\x18\x01 \x01(\tR\x04mess2I\n" +
	"\x06Health\x12?\n" +
	"\x04Ping\x12\x0f.health.Request\x1a\x10.health.Response\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/api/v1/pingB!Z\x1f./manager-api/proto;manager_apib\x06proto3"

var (
	file_manager_api_api_health_proto_rawDescOnce sync.Once
	file_manager_api_api_health_proto_rawDescData []byte
)

func file_manager_api_api_health_proto_rawDescGZIP() []byte {
	file_manager_api_api_health_proto_rawDescOnce.Do(func() {
		file_manager_api_api_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_manager_api_api_health_proto_rawDesc), len(file_manager_api_api_health_proto_rawDesc)))
	})
	return file_manager_api_api_health_proto_rawDescData
}

var file_manager_api_api_health_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_manager_api_api_health_proto_goTypes = []any{
	(*Request)(nil),  // 0: health.Request
	(*Response)(nil), // 1: health.Response
}
var file_manager_api_api_health_proto_depIdxs = []int32{
	0, // 0: health.Health.Ping:input_type -> health.Request
	1, // 1: health.Health.Ping:output_type -> health.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_manager_api_api_health_proto_init() }
func file_manager_api_api_health_proto_init() {
	if File_manager_api_api_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_manager_api_api_health_proto_rawDesc), len(file_manager_api_api_health_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_manager_api_api_health_proto_goTypes,
		DependencyIndexes: file_manager_api_api_health_proto_depIdxs,
		MessageInfos:      file_manager_api_api_health_proto_msgTypes,
	}.Build()
	File_manager_api_api_health_proto = out.File
	file_manager_api_api_health_proto_goTypes = nil
	file_manager_api_api_health_proto_depIdxs = nil
}
