// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: manager-api/api/movie_theater.proto

package manager_api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// api: create
type CreateMovieTheaterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMovieTheaterReq) Reset() {
	*x = CreateMovieTheaterReq{}
	mi := &file_manager_api_api_movie_theater_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMovieTheaterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMovieTheaterReq) ProtoMessage() {}

func (x *CreateMovieTheaterReq) ProtoReflect() protoreflect.Message {
	mi := &file_manager_api_api_movie_theater_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMovieTheaterReq.ProtoReflect.Descriptor instead.
func (*CreateMovieTheaterReq) Descriptor() ([]byte, []int) {
	return file_manager_api_api_movie_theater_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMovieTheaterReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMovieTheaterReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type CreateMovieTheaterRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMovieTheaterRes) Reset() {
	*x = CreateMovieTheaterRes{}
	mi := &file_manager_api_api_movie_theater_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMovieTheaterRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMovieTheaterRes) ProtoMessage() {}

func (x *CreateMovieTheaterRes) ProtoReflect() protoreflect.Message {
	mi := &file_manager_api_api_movie_theater_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMovieTheaterRes.ProtoReflect.Descriptor instead.
func (*CreateMovieTheaterRes) Descriptor() ([]byte, []int) {
	return file_manager_api_api_movie_theater_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMovieTheaterRes) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *CreateMovieTheaterRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMovieTheaterRes) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// api: update
type UpdateMovieTheaterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMovieTheaterReq) Reset() {
	*x = UpdateMovieTheaterReq{}
	mi := &file_manager_api_api_movie_theater_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMovieTheaterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMovieTheaterReq) ProtoMessage() {}

func (x *UpdateMovieTheaterReq) ProtoReflect() protoreflect.Message {
	mi := &file_manager_api_api_movie_theater_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMovieTheaterReq.ProtoReflect.Descriptor instead.
func (*UpdateMovieTheaterReq) Descriptor() ([]byte, []int) {
	return file_manager_api_api_movie_theater_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateMovieTheaterReq) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UpdateMovieTheaterReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateMovieTheaterReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type UpdateMovieTheaterRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMovieTheaterRes) Reset() {
	*x = UpdateMovieTheaterRes{}
	mi := &file_manager_api_api_movie_theater_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMovieTheaterRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMovieTheaterRes) ProtoMessage() {}

func (x *UpdateMovieTheaterRes) ProtoReflect() protoreflect.Message {
	mi := &file_manager_api_api_movie_theater_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMovieTheaterRes.ProtoReflect.Descriptor instead.
func (*UpdateMovieTheaterRes) Descriptor() ([]byte, []int) {
	return file_manager_api_api_movie_theater_proto_rawDescGZIP(), []int{3}
}

// api: get list
type GetListMovieTheaterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilterBase    *FilterBase            `protobuf:"bytes,1,opt,name=filter_base,json=filterBase,proto3" json:"filter_base,omitempty"`
	Filter        *MovieTheaterFilterReq `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListMovieTheaterReq) Reset() {
	*x = GetListMovieTheaterReq{}
	mi := &file_manager_api_api_movie_theater_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListMovieTheaterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListMovieTheaterReq) ProtoMessage() {}

func (x *GetListMovieTheaterReq) ProtoReflect() protoreflect.Message {
	mi := &file_manager_api_api_movie_theater_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListMovieTheaterReq.ProtoReflect.Descriptor instead.
func (*GetListMovieTheaterReq) Descriptor() ([]byte, []int) {
	return file_manager_api_api_movie_theater_proto_rawDescGZIP(), []int{4}
}

func (x *GetListMovieTheaterReq) GetFilterBase() *FilterBase {
	if x != nil {
		return x.FilterBase
	}
	return nil
}

func (x *GetListMovieTheaterReq) GetFilter() *MovieTheaterFilterReq {
	if x != nil {
		return x.Filter
	}
	return nil
}

type MovieTheaterFilterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieTheaterFilterReq) Reset() {
	*x = MovieTheaterFilterReq{}
	mi := &file_manager_api_api_movie_theater_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieTheaterFilterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieTheaterFilterReq) ProtoMessage() {}

func (x *MovieTheaterFilterReq) ProtoReflect() protoreflect.Message {
	mi := &file_manager_api_api_movie_theater_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieTheaterFilterReq.ProtoReflect.Descriptor instead.
func (*MovieTheaterFilterReq) Descriptor() ([]byte, []int) {
	return file_manager_api_api_movie_theater_proto_rawDescGZIP(), []int{5}
}

func (x *MovieTheaterFilterReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MovieTheaterFilterReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetListMovieTheaterRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*MovieTheaterRes     `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListMovieTheaterRes) Reset() {
	*x = GetListMovieTheaterRes{}
	mi := &file_manager_api_api_movie_theater_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListMovieTheaterRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListMovieTheaterRes) ProtoMessage() {}

func (x *GetListMovieTheaterRes) ProtoReflect() protoreflect.Message {
	mi := &file_manager_api_api_movie_theater_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListMovieTheaterRes.ProtoReflect.Descriptor instead.
func (*GetListMovieTheaterRes) Descriptor() ([]byte, []int) {
	return file_manager_api_api_movie_theater_proto_rawDescGZIP(), []int{6}
}

func (x *GetListMovieTheaterRes) GetData() []*MovieTheaterRes {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetListMovieTheaterRes) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type MovieTheaterRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	CreaterId     string                 `protobuf:"bytes,4,opt,name=creater_id,json=createrId,proto3" json:"creater_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieTheaterRes) Reset() {
	*x = MovieTheaterRes{}
	mi := &file_manager_api_api_movie_theater_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieTheaterRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieTheaterRes) ProtoMessage() {}

func (x *MovieTheaterRes) ProtoReflect() protoreflect.Message {
	mi := &file_manager_api_api_movie_theater_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieTheaterRes.ProtoReflect.Descriptor instead.
func (*MovieTheaterRes) Descriptor() ([]byte, []int) {
	return file_manager_api_api_movie_theater_proto_rawDescGZIP(), []int{7}
}

func (x *MovieTheaterRes) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *MovieTheaterRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MovieTheaterRes) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *MovieTheaterRes) GetCreaterId() string {
	if x != nil {
		return x.CreaterId
	}
	return ""
}

// api: detail
type DetailMovieTheaterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailMovieTheaterReq) Reset() {
	*x = DetailMovieTheaterReq{}
	mi := &file_manager_api_api_movie_theater_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailMovieTheaterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailMovieTheaterReq) ProtoMessage() {}

func (x *DetailMovieTheaterReq) ProtoReflect() protoreflect.Message {
	mi := &file_manager_api_api_movie_theater_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailMovieTheaterReq.ProtoReflect.Descriptor instead.
func (*DetailMovieTheaterReq) Descriptor() ([]byte, []int) {
	return file_manager_api_api_movie_theater_proto_rawDescGZIP(), []int{8}
}

func (x *DetailMovieTheaterReq) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type DetailMovieTheaterRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	CreaterId     string                 `protobuf:"bytes,4,opt,name=creater_id,json=createrId,proto3" json:"creater_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailMovieTheaterRes) Reset() {
	*x = DetailMovieTheaterRes{}
	mi := &file_manager_api_api_movie_theater_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailMovieTheaterRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailMovieTheaterRes) ProtoMessage() {}

func (x *DetailMovieTheaterRes) ProtoReflect() protoreflect.Message {
	mi := &file_manager_api_api_movie_theater_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailMovieTheaterRes.ProtoReflect.Descriptor instead.
func (*DetailMovieTheaterRes) Descriptor() ([]byte, []int) {
	return file_manager_api_api_movie_theater_proto_rawDescGZIP(), []int{9}
}

func (x *DetailMovieTheaterRes) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *DetailMovieTheaterRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DetailMovieTheaterRes) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DetailMovieTheaterRes) GetCreaterId() string {
	if x != nil {
		return x.CreaterId
	}
	return ""
}

func (x *DetailMovieTheaterRes) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *DetailMovieTheaterRes) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_manager_api_api_movie_theater_proto protoreflect.FileDescriptor

const file_manager_api_api_movie_theater_proto_rawDesc = "" +
	"\n" +
	"#manager-api/api/movie_theater.proto\x12\rmovie_theater\x1a(third-party/google/api/annotations.proto\x1a\x1cmanager-api/api/common.proto\"E\n" +
	"\x15CreateMovieTheaterReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"Y\n" +
	"\x15CreateMovieTheaterRes\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"Y\n" +
	"\x15UpdateMovieTheaterReq\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"\x17\n" +
	"\x15UpdateMovieTheaterRes\"\x8b\x01\n" +
	"\x16GetListMovieTheaterReq\x123\n" +
	"\vfilter_base\x18\x01 \x01(\v2\x12.common.FilterBaseR\n" +
	"filterBase\x12<\n" +
	"\x06filter\x18\x02 \x01(\v2$.movie_theater.MovieTheaterFilterReqR\x06filter\"E\n" +
	"\x15MovieTheaterFilterReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"b\n" +
	"\x16GetListMovieTheaterRes\x122\n" +
	"\x04data\x18\x01 \x03(\v2\x1e.movie_theater.MovieTheaterResR\x04data\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"r\n" +
	"\x0fMovieTheaterRes\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"creater_id\x18\x04 \x01(\tR\tcreaterId\"+\n" +
	"\x15DetailMovieTheaterReq\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\xb6\x01\n" +
	"\x15DetailMovieTheaterRes\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"creater_id\x18\x04 \x01(\tR\tcreaterId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt2\x83\x04\n" +
	"\fMovieTheater\x12}\n" +
	"\x06Create\x12$.movie_theater.CreateMovieTheaterReq\x1a$.movie_theater.CreateMovieTheaterRes\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/v1/movie-theater/create\x12}\n" +
	"\x06Update\x12$.movie_theater.UpdateMovieTheaterReq\x1a$.movie_theater.UpdateMovieTheaterRes\"'\x82\xd3\xe4\x93\x02!:\x01*\x1a\x1c/api/v1/movie-theater/update\x12y\n" +
	"\aGetList\x12%.movie_theater.GetListMovieTheaterReq\x1a%.movie_theater.GetListMovieTheaterRes\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/movie-theater\x12z\n" +
	"\x06Detail\x12$.movie_theater.DetailMovieTheaterReq\x1a$.movie_theater.DetailMovieTheaterRes\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/v1/movie-theater/{uuid}B!Z\x1f./manager-api/proto;manager_apib\x06proto3"

var (
	file_manager_api_api_movie_theater_proto_rawDescOnce sync.Once
	file_manager_api_api_movie_theater_proto_rawDescData []byte
)

func file_manager_api_api_movie_theater_proto_rawDescGZIP() []byte {
	file_manager_api_api_movie_theater_proto_rawDescOnce.Do(func() {
		file_manager_api_api_movie_theater_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_manager_api_api_movie_theater_proto_rawDesc), len(file_manager_api_api_movie_theater_proto_rawDesc)))
	})
	return file_manager_api_api_movie_theater_proto_rawDescData
}

var file_manager_api_api_movie_theater_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_manager_api_api_movie_theater_proto_goTypes = []any{
	(*CreateMovieTheaterReq)(nil),  // 0: movie_theater.CreateMovieTheaterReq
	(*CreateMovieTheaterRes)(nil),  // 1: movie_theater.CreateMovieTheaterRes
	(*UpdateMovieTheaterReq)(nil),  // 2: movie_theater.UpdateMovieTheaterReq
	(*UpdateMovieTheaterRes)(nil),  // 3: movie_theater.UpdateMovieTheaterRes
	(*GetListMovieTheaterReq)(nil), // 4: movie_theater.GetListMovieTheaterReq
	(*MovieTheaterFilterReq)(nil),  // 5: movie_theater.MovieTheaterFilterReq
	(*GetListMovieTheaterRes)(nil), // 6: movie_theater.GetListMovieTheaterRes
	(*MovieTheaterRes)(nil),        // 7: movie_theater.MovieTheaterRes
	(*DetailMovieTheaterReq)(nil),  // 8: movie_theater.DetailMovieTheaterReq
	(*DetailMovieTheaterRes)(nil),  // 9: movie_theater.DetailMovieTheaterRes
	(*FilterBase)(nil),             // 10: common.FilterBase
}
var file_manager_api_api_movie_theater_proto_depIdxs = []int32{
	10, // 0: movie_theater.GetListMovieTheaterReq.filter_base:type_name -> common.FilterBase
	5,  // 1: movie_theater.GetListMovieTheaterReq.filter:type_name -> movie_theater.MovieTheaterFilterReq
	7,  // 2: movie_theater.GetListMovieTheaterRes.data:type_name -> movie_theater.MovieTheaterRes
	0,  // 3: movie_theater.MovieTheater.Create:input_type -> movie_theater.CreateMovieTheaterReq
	2,  // 4: movie_theater.MovieTheater.Update:input_type -> movie_theater.UpdateMovieTheaterReq
	4,  // 5: movie_theater.MovieTheater.GetList:input_type -> movie_theater.GetListMovieTheaterReq
	8,  // 6: movie_theater.MovieTheater.Detail:input_type -> movie_theater.DetailMovieTheaterReq
	1,  // 7: movie_theater.MovieTheater.Create:output_type -> movie_theater.CreateMovieTheaterRes
	3,  // 8: movie_theater.MovieTheater.Update:output_type -> movie_theater.UpdateMovieTheaterRes
	6,  // 9: movie_theater.MovieTheater.GetList:output_type -> movie_theater.GetListMovieTheaterRes
	9,  // 10: movie_theater.MovieTheater.Detail:output_type -> movie_theater.DetailMovieTheaterRes
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_manager_api_api_movie_theater_proto_init() }
func file_manager_api_api_movie_theater_proto_init() {
	if File_manager_api_api_movie_theater_proto != nil {
		return
	}
	file_manager_api_api_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_manager_api_api_movie_theater_proto_rawDesc), len(file_manager_api_api_movie_theater_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_manager_api_api_movie_theater_proto_goTypes,
		DependencyIndexes: file_manager_api_api_movie_theater_proto_depIdxs,
		MessageInfos:      file_manager_api_api_movie_theater_proto_msgTypes,
	}.Build()
	File_manager_api_api_movie_theater_proto = out.File
	file_manager_api_api_movie_theater_proto_goTypes = nil
	file_manager_api_api_movie_theater_proto_depIdxs = nil
}
