// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: manager-api/api/show_time.proto

package manager_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Showtime_Create_FullMethodName = "/show_time.Showtime/Create"
	Showtime_List_FullMethodName   = "/show_time.Showtime/List"
)

// ShowtimeClient is the client API for Showtime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShowtimeClient interface {
	Create(ctx context.Context, in *CreateShowtimeReq, opts ...grpc.CallOption) (*CreateShowtimeRes, error)
	List(ctx context.Context, in *ListShowtimeReq, opts ...grpc.CallOption) (*ListShowtimeRes, error)
}

type showtimeClient struct {
	cc grpc.ClientConnInterface
}

func NewShowtimeClient(cc grpc.ClientConnInterface) ShowtimeClient {
	return &showtimeClient{cc}
}

func (c *showtimeClient) Create(ctx context.Context, in *CreateShowtimeReq, opts ...grpc.CallOption) (*CreateShowtimeRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateShowtimeRes)
	err := c.cc.Invoke(ctx, Showtime_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *showtimeClient) List(ctx context.Context, in *ListShowtimeReq, opts ...grpc.CallOption) (*ListShowtimeRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListShowtimeRes)
	err := c.cc.Invoke(ctx, Showtime_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShowtimeServer is the server API for Showtime service.
// All implementations must embed UnimplementedShowtimeServer
// for forward compatibility.
type ShowtimeServer interface {
	Create(context.Context, *CreateShowtimeReq) (*CreateShowtimeRes, error)
	List(context.Context, *ListShowtimeReq) (*ListShowtimeRes, error)
	mustEmbedUnimplementedShowtimeServer()
}

// UnimplementedShowtimeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShowtimeServer struct{}

func (UnimplementedShowtimeServer) Create(context.Context, *CreateShowtimeReq) (*CreateShowtimeRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedShowtimeServer) List(context.Context, *ListShowtimeReq) (*ListShowtimeRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedShowtimeServer) mustEmbedUnimplementedShowtimeServer() {}
func (UnimplementedShowtimeServer) testEmbeddedByValue()                  {}

// UnsafeShowtimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShowtimeServer will
// result in compilation errors.
type UnsafeShowtimeServer interface {
	mustEmbedUnimplementedShowtimeServer()
}

func RegisterShowtimeServer(s grpc.ServiceRegistrar, srv ShowtimeServer) {
	// If the following call pancis, it indicates UnimplementedShowtimeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Showtime_ServiceDesc, srv)
}

func _Showtime_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShowtimeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShowtimeServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Showtime_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShowtimeServer).Create(ctx, req.(*CreateShowtimeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Showtime_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListShowtimeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShowtimeServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Showtime_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShowtimeServer).List(ctx, req.(*ListShowtimeReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Showtime_ServiceDesc is the grpc.ServiceDesc for Showtime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Showtime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "show_time.Showtime",
	HandlerType: (*ShowtimeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Showtime_Create_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Showtime_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "manager-api/api/show_time.proto",
}
