// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: manager-api/api/show_time.proto

package manager_api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateShowtimeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*ShowtimeModel       `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShowtimeReq) Reset() {
	*x = CreateShowtimeReq{}
	mi := &file_manager_api_api_show_time_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShowtimeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShowtimeReq) ProtoMessage() {}

func (x *CreateShowtimeReq) ProtoReflect() protoreflect.Message {
	mi := &file_manager_api_api_show_time_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShowtimeReq.ProtoReflect.Descriptor instead.
func (*CreateShowtimeReq) Descriptor() ([]byte, []int) {
	return file_manager_api_api_show_time_proto_rawDescGZIP(), []int{0}
}

func (x *CreateShowtimeReq) GetData() []*ShowtimeModel {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateShowtimeRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*ShowtimeModel       `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShowtimeRes) Reset() {
	*x = CreateShowtimeRes{}
	mi := &file_manager_api_api_show_time_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShowtimeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShowtimeRes) ProtoMessage() {}

func (x *CreateShowtimeRes) ProtoReflect() protoreflect.Message {
	mi := &file_manager_api_api_show_time_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShowtimeRes.ProtoReflect.Descriptor instead.
func (*CreateShowtimeRes) Descriptor() ([]byte, []int) {
	return file_manager_api_api_show_time_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShowtimeRes) GetData() []*ShowtimeModel {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListShowtimeReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MovieTheaterId string                 `protobuf:"bytes,1,opt,name=movie_theater_id,json=movieTheaterId,proto3" json:"movie_theater_id,omitempty"`
	CinemaroomId   string                 `protobuf:"bytes,2,opt,name=cinemaroom_id,json=cinemaroomId,proto3" json:"cinemaroom_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListShowtimeReq) Reset() {
	*x = ListShowtimeReq{}
	mi := &file_manager_api_api_show_time_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShowtimeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShowtimeReq) ProtoMessage() {}

func (x *ListShowtimeReq) ProtoReflect() protoreflect.Message {
	mi := &file_manager_api_api_show_time_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShowtimeReq.ProtoReflect.Descriptor instead.
func (*ListShowtimeReq) Descriptor() ([]byte, []int) {
	return file_manager_api_api_show_time_proto_rawDescGZIP(), []int{2}
}

func (x *ListShowtimeReq) GetMovieTheaterId() string {
	if x != nil {
		return x.MovieTheaterId
	}
	return ""
}

func (x *ListShowtimeReq) GetCinemaroomId() string {
	if x != nil {
		return x.CinemaroomId
	}
	return ""
}

type ListShowtimeRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*ShowtimeModel       `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShowtimeRes) Reset() {
	*x = ListShowtimeRes{}
	mi := &file_manager_api_api_show_time_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShowtimeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShowtimeRes) ProtoMessage() {}

func (x *ListShowtimeRes) ProtoReflect() protoreflect.Message {
	mi := &file_manager_api_api_show_time_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShowtimeRes.ProtoReflect.Descriptor instead.
func (*ListShowtimeRes) Descriptor() ([]byte, []int) {
	return file_manager_api_api_show_time_proto_rawDescGZIP(), []int{3}
}

func (x *ListShowtimeRes) GetData() []*ShowtimeModel {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_manager_api_api_show_time_proto protoreflect.FileDescriptor

const file_manager_api_api_show_time_proto_rawDesc = "" +
	"\n" +
	"\x1fmanager-api/api/show_time.proto\x12\tshow_time\x1a\x1bmanager-api/api/model.proto\x1a(third-party/google/api/annotations.proto\"=\n" +
	"\x11CreateShowtimeReq\x12(\n" +
	"\x04data\x18\x01 \x03(\v2\x14.model.ShowtimeModelR\x04data\"=\n" +
	"\x11CreateShowtimeRes\x12(\n" +
	"\x04data\x18\x01 \x03(\v2\x14.model.ShowtimeModelR\x04data\"`\n" +
	"\x0fListShowtimeReq\x12(\n" +
	"\x10movie_theater_id\x18\x01 \x01(\tR\x0emovieTheaterId\x12#\n" +
	"\rcinemaroom_id\x18\x02 \x01(\tR\fcinemaroomId\";\n" +
	"\x0fListShowtimeRes\x12(\n" +
	"\x04data\x18\x01 \x03(\v2\x14.model.ShowtimeModelR\x04data2\xec\x01\n" +
	"\bShowtime\x12b\n" +
	"\x06Create\x12\x1c.show_time.CreateShowtimeReq\x1a\x1c.show_time.CreateShowtimeRes\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/v1/show-time\x12|\n" +
	"\x04List\x12\x1a.show_time.ListShowtimeReq\x1a\x1a.show_time.ListShowtimeRes\"<\x82\xd3\xe4\x93\x026\x124/api/v1/show-time/{movie_theater_id}/{cinemaroom_id}B!Z\x1f./manager-api/proto;manager_apib\x06proto3"

var (
	file_manager_api_api_show_time_proto_rawDescOnce sync.Once
	file_manager_api_api_show_time_proto_rawDescData []byte
)

func file_manager_api_api_show_time_proto_rawDescGZIP() []byte {
	file_manager_api_api_show_time_proto_rawDescOnce.Do(func() {
		file_manager_api_api_show_time_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_manager_api_api_show_time_proto_rawDesc), len(file_manager_api_api_show_time_proto_rawDesc)))
	})
	return file_manager_api_api_show_time_proto_rawDescData
}

var file_manager_api_api_show_time_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_manager_api_api_show_time_proto_goTypes = []any{
	(*CreateShowtimeReq)(nil), // 0: show_time.CreateShowtimeReq
	(*CreateShowtimeRes)(nil), // 1: show_time.CreateShowtimeRes
	(*ListShowtimeReq)(nil),   // 2: show_time.ListShowtimeReq
	(*ListShowtimeRes)(nil),   // 3: show_time.ListShowtimeRes
	(*ShowtimeModel)(nil),     // 4: model.ShowtimeModel
}
var file_manager_api_api_show_time_proto_depIdxs = []int32{
	4, // 0: show_time.CreateShowtimeReq.data:type_name -> model.ShowtimeModel
	4, // 1: show_time.CreateShowtimeRes.data:type_name -> model.ShowtimeModel
	4, // 2: show_time.ListShowtimeRes.data:type_name -> model.ShowtimeModel
	0, // 3: show_time.Showtime.Create:input_type -> show_time.CreateShowtimeReq
	2, // 4: show_time.Showtime.List:input_type -> show_time.ListShowtimeReq
	1, // 5: show_time.Showtime.Create:output_type -> show_time.CreateShowtimeRes
	3, // 6: show_time.Showtime.List:output_type -> show_time.ListShowtimeRes
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_manager_api_api_show_time_proto_init() }
func file_manager_api_api_show_time_proto_init() {
	if File_manager_api_api_show_time_proto != nil {
		return
	}
	file_manager_api_api_model_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_manager_api_api_show_time_proto_rawDesc), len(file_manager_api_api_show_time_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_manager_api_api_show_time_proto_goTypes,
		DependencyIndexes: file_manager_api_api_show_time_proto_depIdxs,
		MessageInfos:      file_manager_api_api_show_time_proto_msgTypes,
	}.Build()
	File_manager_api_api_show_time_proto = out.File
	file_manager_api_api_show_time_proto_goTypes = nil
	file_manager_api_api_show_time_proto_depIdxs = nil
}
