// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: manager-api/api/theater_seating.proto

package manager_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// api: create theater seating
type CreateTheaterSeatingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CinemaRoomId  string                 `protobuf:"bytes,1,opt,name=cinema_room_id,json=cinemaRoomId,proto3" json:"cinema_room_id,omitempty"`
	Theaters      []*TheaterSeatingModel `protobuf:"bytes,2,rep,name=theaters,proto3" json:"theaters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTheaterSeatingReq) Reset() {
	*x = CreateTheaterSeatingReq{}
	mi := &file_manager_api_api_theater_seating_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTheaterSeatingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTheaterSeatingReq) ProtoMessage() {}

func (x *CreateTheaterSeatingReq) ProtoReflect() protoreflect.Message {
	mi := &file_manager_api_api_theater_seating_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTheaterSeatingReq.ProtoReflect.Descriptor instead.
func (*CreateTheaterSeatingReq) Descriptor() ([]byte, []int) {
	return file_manager_api_api_theater_seating_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTheaterSeatingReq) GetCinemaRoomId() string {
	if x != nil {
		return x.CinemaRoomId
	}
	return ""
}

func (x *CreateTheaterSeatingReq) GetTheaters() []*TheaterSeatingModel {
	if x != nil {
		return x.Theaters
	}
	return nil
}

type CreateTheaterSeatingRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListId        []string               `protobuf:"bytes,1,rep,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTheaterSeatingRes) Reset() {
	*x = CreateTheaterSeatingRes{}
	mi := &file_manager_api_api_theater_seating_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTheaterSeatingRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTheaterSeatingRes) ProtoMessage() {}

func (x *CreateTheaterSeatingRes) ProtoReflect() protoreflect.Message {
	mi := &file_manager_api_api_theater_seating_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTheaterSeatingRes.ProtoReflect.Descriptor instead.
func (*CreateTheaterSeatingRes) Descriptor() ([]byte, []int) {
	return file_manager_api_api_theater_seating_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTheaterSeatingRes) GetListId() []string {
	if x != nil {
		return x.ListId
	}
	return nil
}

// api: update theater seating
type UpdateTheaterSeatingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListId        []string               `protobuf:"bytes,1,rep,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
	IsIgnore      bool                   `protobuf:"varint,2,opt,name=is_ignore,json=isIgnore,proto3" json:"is_ignore,omitempty"`
	Theaters      []*TheaterSeatingModel `protobuf:"bytes,3,rep,name=theaters,proto3" json:"theaters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTheaterSeatingReq) Reset() {
	*x = UpdateTheaterSeatingReq{}
	mi := &file_manager_api_api_theater_seating_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTheaterSeatingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTheaterSeatingReq) ProtoMessage() {}

func (x *UpdateTheaterSeatingReq) ProtoReflect() protoreflect.Message {
	mi := &file_manager_api_api_theater_seating_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTheaterSeatingReq.ProtoReflect.Descriptor instead.
func (*UpdateTheaterSeatingReq) Descriptor() ([]byte, []int) {
	return file_manager_api_api_theater_seating_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateTheaterSeatingReq) GetListId() []string {
	if x != nil {
		return x.ListId
	}
	return nil
}

func (x *UpdateTheaterSeatingReq) GetIsIgnore() bool {
	if x != nil {
		return x.IsIgnore
	}
	return false
}

func (x *UpdateTheaterSeatingReq) GetTheaters() []*TheaterSeatingModel {
	if x != nil {
		return x.Theaters
	}
	return nil
}

type UpdateTheaterSeatingRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListId        []string               `protobuf:"bytes,1,rep,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTheaterSeatingRes) Reset() {
	*x = UpdateTheaterSeatingRes{}
	mi := &file_manager_api_api_theater_seating_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTheaterSeatingRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTheaterSeatingRes) ProtoMessage() {}

func (x *UpdateTheaterSeatingRes) ProtoReflect() protoreflect.Message {
	mi := &file_manager_api_api_theater_seating_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTheaterSeatingRes.ProtoReflect.Descriptor instead.
func (*UpdateTheaterSeatingRes) Descriptor() ([]byte, []int) {
	return file_manager_api_api_theater_seating_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateTheaterSeatingRes) GetListId() []string {
	if x != nil {
		return x.ListId
	}
	return nil
}

// api: list theater seating
type FilterListTheaterSeating struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CinemaRoomId  string                 `protobuf:"bytes,1,opt,name=cinema_room_id,json=cinemaRoomId,proto3" json:"cinema_room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterListTheaterSeating) Reset() {
	*x = FilterListTheaterSeating{}
	mi := &file_manager_api_api_theater_seating_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterListTheaterSeating) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterListTheaterSeating) ProtoMessage() {}

func (x *FilterListTheaterSeating) ProtoReflect() protoreflect.Message {
	mi := &file_manager_api_api_theater_seating_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterListTheaterSeating.ProtoReflect.Descriptor instead.
func (*FilterListTheaterSeating) Descriptor() ([]byte, []int) {
	return file_manager_api_api_theater_seating_proto_rawDescGZIP(), []int{4}
}

func (x *FilterListTheaterSeating) GetCinemaRoomId() string {
	if x != nil {
		return x.CinemaRoomId
	}
	return ""
}

type ListTheaterSeatingReq struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	FilterBase    *FilterBase               `protobuf:"bytes,1,opt,name=filter_base,json=filterBase,proto3" json:"filter_base,omitempty"`
	Filter        *FilterListTheaterSeating `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTheaterSeatingReq) Reset() {
	*x = ListTheaterSeatingReq{}
	mi := &file_manager_api_api_theater_seating_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTheaterSeatingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTheaterSeatingReq) ProtoMessage() {}

func (x *ListTheaterSeatingReq) ProtoReflect() protoreflect.Message {
	mi := &file_manager_api_api_theater_seating_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTheaterSeatingReq.ProtoReflect.Descriptor instead.
func (*ListTheaterSeatingReq) Descriptor() ([]byte, []int) {
	return file_manager_api_api_theater_seating_proto_rawDescGZIP(), []int{5}
}

func (x *ListTheaterSeatingReq) GetFilterBase() *FilterBase {
	if x != nil {
		return x.FilterBase
	}
	return nil
}

func (x *ListTheaterSeatingReq) GetFilter() *FilterListTheaterSeating {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListTheaterSeatingRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data          []*TheaterSeatingModel `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTheaterSeatingRes) Reset() {
	*x = ListTheaterSeatingRes{}
	mi := &file_manager_api_api_theater_seating_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTheaterSeatingRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTheaterSeatingRes) ProtoMessage() {}

func (x *ListTheaterSeatingRes) ProtoReflect() protoreflect.Message {
	mi := &file_manager_api_api_theater_seating_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTheaterSeatingRes.ProtoReflect.Descriptor instead.
func (*ListTheaterSeatingRes) Descriptor() ([]byte, []int) {
	return file_manager_api_api_theater_seating_proto_rawDescGZIP(), []int{6}
}

func (x *ListTheaterSeatingRes) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListTheaterSeatingRes) GetData() []*TheaterSeatingModel {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_manager_api_api_theater_seating_proto protoreflect.FileDescriptor

const file_manager_api_api_theater_seating_proto_rawDesc = "" +
	"\n" +
	"%manager-api/api/theater_seating.proto\x12\x0ftheater_seating\x1a\x1bmanager-api/api/model.proto\x1a\x1cmanager-api/api/common.proto\"w\n" +
	"\x17CreateTheaterSeatingReq\x12$\n" +
	"\x0ecinema_room_id\x18\x01 \x01(\tR\fcinemaRoomId\x126\n" +
	"\btheaters\x18\x02 \x03(\v2\x1a.model.TheaterSeatingModelR\btheaters\"2\n" +
	"\x17CreateTheaterSeatingRes\x12\x17\n" +
	"\alist_id\x18\x01 \x03(\tR\x06listId\"\x87\x01\n" +
	"\x17UpdateTheaterSeatingReq\x12\x17\n" +
	"\alist_id\x18\x01 \x03(\tR\x06listId\x12\x1b\n" +
	"\tis_ignore\x18\x02 \x01(\bR\bisIgnore\x126\n" +
	"\btheaters\x18\x03 \x03(\v2\x1a.model.TheaterSeatingModelR\btheaters\"2\n" +
	"\x17UpdateTheaterSeatingRes\x12\x17\n" +
	"\alist_id\x18\x01 \x03(\tR\x06listId\"@\n" +
	"\x18FilterListTheaterSeating\x12$\n" +
	"\x0ecinema_room_id\x18\x01 \x01(\tR\fcinemaRoomId\"\x8f\x01\n" +
	"\x15ListTheaterSeatingReq\x123\n" +
	"\vfilter_base\x18\x01 \x01(\v2\x12.common.FilterBaseR\n" +
	"filterBase\x12A\n" +
	"\x06filter\x18\x02 \x01(\v2).theater_seating.FilterListTheaterSeatingR\x06filter\"]\n" +
	"\x15ListTheaterSeatingRes\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12.\n" +
	"\x04data\x18\x02 \x03(\v2\x1a.model.TheaterSeatingModelR\x04dataB!Z\x1f./manager-api/proto;manager_apib\x06proto3"

var (
	file_manager_api_api_theater_seating_proto_rawDescOnce sync.Once
	file_manager_api_api_theater_seating_proto_rawDescData []byte
)

func file_manager_api_api_theater_seating_proto_rawDescGZIP() []byte {
	file_manager_api_api_theater_seating_proto_rawDescOnce.Do(func() {
		file_manager_api_api_theater_seating_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_manager_api_api_theater_seating_proto_rawDesc), len(file_manager_api_api_theater_seating_proto_rawDesc)))
	})
	return file_manager_api_api_theater_seating_proto_rawDescData
}

var file_manager_api_api_theater_seating_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_manager_api_api_theater_seating_proto_goTypes = []any{
	(*CreateTheaterSeatingReq)(nil),  // 0: theater_seating.CreateTheaterSeatingReq
	(*CreateTheaterSeatingRes)(nil),  // 1: theater_seating.CreateTheaterSeatingRes
	(*UpdateTheaterSeatingReq)(nil),  // 2: theater_seating.UpdateTheaterSeatingReq
	(*UpdateTheaterSeatingRes)(nil),  // 3: theater_seating.UpdateTheaterSeatingRes
	(*FilterListTheaterSeating)(nil), // 4: theater_seating.FilterListTheaterSeating
	(*ListTheaterSeatingReq)(nil),    // 5: theater_seating.ListTheaterSeatingReq
	(*ListTheaterSeatingRes)(nil),    // 6: theater_seating.ListTheaterSeatingRes
	(*TheaterSeatingModel)(nil),      // 7: model.TheaterSeatingModel
	(*FilterBase)(nil),               // 8: common.FilterBase
}
var file_manager_api_api_theater_seating_proto_depIdxs = []int32{
	7, // 0: theater_seating.CreateTheaterSeatingReq.theaters:type_name -> model.TheaterSeatingModel
	7, // 1: theater_seating.UpdateTheaterSeatingReq.theaters:type_name -> model.TheaterSeatingModel
	8, // 2: theater_seating.ListTheaterSeatingReq.filter_base:type_name -> common.FilterBase
	4, // 3: theater_seating.ListTheaterSeatingReq.filter:type_name -> theater_seating.FilterListTheaterSeating
	7, // 4: theater_seating.ListTheaterSeatingRes.data:type_name -> model.TheaterSeatingModel
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_manager_api_api_theater_seating_proto_init() }
func file_manager_api_api_theater_seating_proto_init() {
	if File_manager_api_api_theater_seating_proto != nil {
		return
	}
	file_manager_api_api_model_proto_init()
	file_manager_api_api_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_manager_api_api_theater_seating_proto_rawDesc), len(file_manager_api_api_theater_seating_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_manager_api_api_theater_seating_proto_goTypes,
		DependencyIndexes: file_manager_api_api_theater_seating_proto_depIdxs,
		MessageInfos:      file_manager_api_api_theater_seating_proto_msgTypes,
	}.Build()
	File_manager_api_api_theater_seating_proto = out.File
	file_manager_api_api_theater_seating_proto_goTypes = nil
	file_manager_api_api_theater_seating_proto_depIdxs = nil
}
