// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: file-api/api/common.proto

package file_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FilterBase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterBase) Reset() {
	*x = FilterBase{}
	mi := &file_file_api_api_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterBase) ProtoMessage() {}

func (x *FilterBase) ProtoReflect() protoreflect.Message {
	mi := &file_file_api_api_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterBase.ProtoReflect.Descriptor instead.
func (*FilterBase) Descriptor() ([]byte, []int) {
	return file_file_api_api_common_proto_rawDescGZIP(), []int{0}
}

func (x *FilterBase) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FilterBase) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type Context struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Context) Reset() {
	*x = Context{}
	mi := &file_file_api_api_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Context) ProtoMessage() {}

func (x *Context) ProtoReflect() protoreflect.Message {
	mi := &file_file_api_api_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Context.ProtoReflect.Descriptor instead.
func (*Context) Descriptor() ([]byte, []int) {
	return file_file_api_api_common_proto_rawDescGZIP(), []int{1}
}

func (x *Context) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_file_api_api_common_proto protoreflect.FileDescriptor

const file_file_api_api_common_proto_rawDesc = "" +
	"\n" +
	"\x19file-api/api/common.proto\x12\x06common\":\n" +
	"\n" +
	"FilterBase\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"\"\n" +
	"\aContext\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userIdB\x1bZ\x19./file-api/proto;file_apib\x06proto3"

var (
	file_file_api_api_common_proto_rawDescOnce sync.Once
	file_file_api_api_common_proto_rawDescData []byte
)

func file_file_api_api_common_proto_rawDescGZIP() []byte {
	file_file_api_api_common_proto_rawDescOnce.Do(func() {
		file_file_api_api_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_api_api_common_proto_rawDesc), len(file_file_api_api_common_proto_rawDesc)))
	})
	return file_file_api_api_common_proto_rawDescData
}

var file_file_api_api_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_file_api_api_common_proto_goTypes = []any{
	(*FilterBase)(nil), // 0: common.FilterBase
	(*Context)(nil),    // 1: common.Context
}
var file_file_api_api_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_file_api_api_common_proto_init() }
func file_file_api_api_common_proto_init() {
	if File_file_api_api_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_api_api_common_proto_rawDesc), len(file_file_api_api_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_file_api_api_common_proto_goTypes,
		DependencyIndexes: file_file_api_api_common_proto_depIdxs,
		MessageInfos:      file_file_api_api_common_proto_msgTypes,
	}.Build()
	File_file_api_api_common_proto = out.File
	file_file_api_api_common_proto_goTypes = nil
	file_file_api_api_common_proto_depIdxs = nil
}
