// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: file-api/api/file.proto

package file_api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTicketFileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *Context               `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	Data          []*FileModel           `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTicketFileReq) Reset() {
	*x = CreateTicketFileReq{}
	mi := &file_file_api_api_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTicketFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTicketFileReq) ProtoMessage() {}

func (x *CreateTicketFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_file_api_api_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTicketFileReq.ProtoReflect.Descriptor instead.
func (*CreateTicketFileReq) Descriptor() ([]byte, []int) {
	return file_file_api_api_file_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTicketFileReq) GetCtx() *Context {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *CreateTicketFileReq) GetData() []*FileModel {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateTicketFileRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*FileModel           `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTicketFileRes) Reset() {
	*x = CreateTicketFileRes{}
	mi := &file_file_api_api_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTicketFileRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTicketFileRes) ProtoMessage() {}

func (x *CreateTicketFileRes) ProtoReflect() protoreflect.Message {
	mi := &file_file_api_api_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTicketFileRes.ProtoReflect.Descriptor instead.
func (*CreateTicketFileRes) Descriptor() ([]byte, []int) {
	return file_file_api_api_file_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTicketFileRes) GetData() []*FileModel {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_file_api_api_file_proto protoreflect.FileDescriptor

const file_file_api_api_file_proto_rawDesc = "" +
	"\n" +
	"\x17file-api/api/file.proto\x12\bfile_api\x1a\x19file-api/api/common.proto\x1a\x18file-api/api/model.proto\x1a(third-party/google/api/annotations.proto\"^\n" +
	"\x13CreateTicketFileReq\x12!\n" +
	"\x03ctx\x18\x01 \x01(\v2\x0f.common.ContextR\x03ctx\x12$\n" +
	"\x04data\x18\x02 \x03(\v2\x10.model.FileModelR\x04data\";\n" +
	"\x13CreateTicketFileRes\x12$\n" +
	"\x04data\x18\x01 \x03(\v2\x10.model.FileModelR\x04data2r\n" +
	"\x04File\x12j\n" +
	"\x06Create\x12\x1d.file_api.CreateTicketFileReq\x1a\x1d.file_api.CreateTicketFileRes\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/file-api/createB\x1bZ\x19./file-api/proto;file_apib\x06proto3"

var (
	file_file_api_api_file_proto_rawDescOnce sync.Once
	file_file_api_api_file_proto_rawDescData []byte
)

func file_file_api_api_file_proto_rawDescGZIP() []byte {
	file_file_api_api_file_proto_rawDescOnce.Do(func() {
		file_file_api_api_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_api_api_file_proto_rawDesc), len(file_file_api_api_file_proto_rawDesc)))
	})
	return file_file_api_api_file_proto_rawDescData
}

var file_file_api_api_file_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_file_api_api_file_proto_goTypes = []any{
	(*CreateTicketFileReq)(nil), // 0: file_api.CreateTicketFileReq
	(*CreateTicketFileRes)(nil), // 1: file_api.CreateTicketFileRes
	(*Context)(nil),             // 2: common.Context
	(*FileModel)(nil),           // 3: model.FileModel
}
var file_file_api_api_file_proto_depIdxs = []int32{
	2, // 0: file_api.CreateTicketFileReq.ctx:type_name -> common.Context
	3, // 1: file_api.CreateTicketFileReq.data:type_name -> model.FileModel
	3, // 2: file_api.CreateTicketFileRes.data:type_name -> model.FileModel
	0, // 3: file_api.File.Create:input_type -> file_api.CreateTicketFileReq
	1, // 4: file_api.File.Create:output_type -> file_api.CreateTicketFileRes
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_file_api_api_file_proto_init() }
func file_file_api_api_file_proto_init() {
	if File_file_api_api_file_proto != nil {
		return
	}
	file_file_api_api_common_proto_init()
	file_file_api_api_model_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_api_api_file_proto_rawDesc), len(file_file_api_api_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_file_api_api_file_proto_goTypes,
		DependencyIndexes: file_file_api_api_file_proto_depIdxs,
		MessageInfos:      file_file_api_api_file_proto_msgTypes,
	}.Build()
	File_file_api_api_file_proto = out.File
	file_file_api_api_file_proto_goTypes = nil
	file_file_api_api_file_proto_depIdxs = nil
}
