// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: file-api/api/model.proto

package file_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	TargetId      string                 `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	FileType      string                 `protobuf:"bytes,5,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	HrefEdit      string                 `protobuf:"bytes,6,opt,name=href_edit,json=hrefEdit,proto3" json:"href_edit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileModel) Reset() {
	*x = FileModel{}
	mi := &file_file_api_api_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileModel) ProtoMessage() {}

func (x *FileModel) ProtoReflect() protoreflect.Message {
	mi := &file_file_api_api_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileModel.ProtoReflect.Descriptor instead.
func (*FileModel) Descriptor() ([]byte, []int) {
	return file_file_api_api_model_proto_rawDescGZIP(), []int{0}
}

func (x *FileModel) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *FileModel) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *FileModel) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *FileModel) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileModel) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *FileModel) GetHrefEdit() string {
	if x != nil {
		return x.HrefEdit
	}
	return ""
}

var File_file_api_api_model_proto protoreflect.FileDescriptor

const file_file_api_api_model_proto_rawDesc = "" +
	"\n" +
	"\x18file-api/api/model.proto\x12\x05model\"\xa0\x01\n" +
	"\tFileModel\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x1b\n" +
	"\tfile_type\x18\x05 \x01(\tR\bfileType\x12\x1b\n" +
	"\thref_edit\x18\x06 \x01(\tR\bhrefEditB\x1bZ\x19./file-api/proto;file_apib\x06proto3"

var (
	file_file_api_api_model_proto_rawDescOnce sync.Once
	file_file_api_api_model_proto_rawDescData []byte
)

func file_file_api_api_model_proto_rawDescGZIP() []byte {
	file_file_api_api_model_proto_rawDescOnce.Do(func() {
		file_file_api_api_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_api_api_model_proto_rawDesc), len(file_file_api_api_model_proto_rawDesc)))
	})
	return file_file_api_api_model_proto_rawDescData
}

var file_file_api_api_model_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_file_api_api_model_proto_goTypes = []any{
	(*FileModel)(nil), // 0: model.FileModel
}
var file_file_api_api_model_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_file_api_api_model_proto_init() }
func file_file_api_api_model_proto_init() {
	if File_file_api_api_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_api_api_model_proto_rawDesc), len(file_file_api_api_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_file_api_api_model_proto_goTypes,
		DependencyIndexes: file_file_api_api_model_proto_depIdxs,
		MessageInfos:      file_file_api_api_model_proto_msgTypes,
	}.Build()
	File_file_api_api_model_proto = out.File
	file_file_api_api_model_proto_goTypes = nil
	file_file_api_api_model_proto_depIdxs = nil
}
